/**
 * The ingredient catalogue that ships with the app: common skin and hair care ingredients by
 * their INCI name (the same in every language), with the names people also search for (aliases,
 * some in Lithuanian) and what each one does (a category, translated as
 * `ingredients.category.<key>`). Autocomplete in ingredient entry (P4) suggests from it alongside
 * the person's own list; it is reference data, not part of their list, so S2 stays theirs.
 *
 * Each entry is a name, or a tuple of the name and its aliases. Names and aliases are unique once
 * normalised (`ingredientCatalog.test.ts` checks).
 */
import { normalizeName } from './text';

export const catalogCategories = [
  'humectant',
  'emollient',
  'oil',
  'barrier',
  'silicone',
  'cleanser',
  'emulsifier',
  'thickener',
  'solvent',
  'preservative',
  'fragrance',
  'phAdjuster',
  'chelator',
  'antioxidant',
  'vitaminC',
  'retinoid',
  'exfoliant',
  'peptide',
  'antiAgeing',
  'soothing',
  'brightening',
  'acne',
  'antiDandruff',
  'sunscreen',
  'colourant',
  'hair',
  'plantExtract',
] as const;

export type CatalogCategory = (typeof catalogCategories)[number];

export type CatalogEntry = { name: string; category: CatalogCategory; aliases: readonly string[] };

type Item = string | readonly [string, ...string[]];

const byCategory: Record<CatalogCategory, readonly Item[]> = {
  humectant: [
    ['Glycerin', 'Glycerol', 'Glicerinas'],
    'Butylene glycol',
    'Propylene glycol',
    'Pentylene glycol',
    'Propanediol',
    ['Hyaluronic acid', 'Hialurono rūgštis'],
    'Sodium hyaluronate',
    'Hydrolyzed hyaluronic acid',
    'Hydrolyzed sodium hyaluronate',
    'Sodium acetylated hyaluronate',
    'Sodium hyaluronate crosspolymer',
    ['Sodium polyglutamate', 'Polyglutamic acid'],
    'Sodium PCA',
    ['Urea', 'Karbamidas', 'Šlapalas'],
    'Hydroxyethyl urea',
    'Betaine',
    'Sorbitol',
    'Trehalose',
    'Xylitol',
    'Erythritol',
    'Inositol',
    'Glyceryl glucoside',
    'Saccharide isomerate',
    'Sodium lactate',
    'Methyl gluceth-20',
    'Glycereth-26',
    ['Panthenol', 'Provitamin B5', 'D-panthenol', 'Dexpanthenol', 'Provitaminas B5'],
    ['Mel', 'Honey', 'Medus'],
    ['Tremella fuciformis polysaccharide', 'Snow mushroom'],
    ['Snail secretion filtrate', 'Snail mucin'],
  ],
  emollient: [
    ['Caprylic/capric triglyceride', 'MCT oil'],
    ['Squalane', 'Skvalanas'],
    'Squalene',
    'Isopropyl myristate',
    'Isopropyl palmitate',
    'Cetearyl alcohol',
    'Cetyl alcohol',
    'Stearyl alcohol',
    'Behenyl alcohol',
    'Cetearyl ethylhexanoate',
    'Ethylhexyl palmitate',
    'Coco-caprylate/caprate',
    'Coco-caprylate',
    'Dicaprylyl carbonate',
    'Dicaprylyl ether',
    'Isononyl isononanoate',
    'C12-15 alkyl benzoate',
    'C13-14 isoparaffin',
    'Isohexadecane',
    'Isododecane',
    'Hydrogenated polyisobutene',
    'Octyldodecanol',
    'Glyceryl caprylate',
    'Diisopropyl adipate',
    'Neopentyl glycol diheptanoate',
    ['Petrolatum', 'Vaseline', 'Petroleum jelly', 'Vazelinas'],
    ['Paraffinum liquidum', 'Mineral oil', 'Liquid paraffin', 'Parafino aliejus'],
    'Lanolin',
    ['Cera alba', 'Beeswax', 'Bičių vaškas'],
    ['Euphorbia cerifera cera', 'Candelilla wax'],
    ['Copernicia cerifera cera', 'Carnauba wax'],
    'Microcrystalline wax',
    ['Butyrospermum parkii butter', 'Shea butter', 'Taukmedžio sviestas'],
    ['Theobroma cacao seed butter', 'Cocoa butter', 'Kakavos sviestas'],
    ['Mangifera indica seed butter', 'Mango butter'],
    'Stearic acid',
    'Palmitic acid',
    'Myristic acid',
    'Lauric acid',
  ],
  oil: [
    ['Simmondsia chinensis seed oil', 'Jojoba oil', 'Jojobos aliejus'],
    ['Argania spinosa kernel oil', 'Argan oil', 'Arganų aliejus'],
    ['Cocos nucifera oil', 'Coconut oil', 'Kokosų aliejus'],
    ['Olea europaea fruit oil', 'Olive oil', 'Alyvuogių aliejus'],
    ['Prunus amygdalus dulcis oil', 'Sweet almond oil', 'Migdolų aliejus'],
    ['Helianthus annuus seed oil', 'Sunflower oil', 'Saulėgrąžų aliejus'],
    ['Rosa canina fruit oil', 'Rosehip oil', 'Erškėtuogių aliejus'],
    ['Rosa rubiginosa seed oil', 'Rosehip seed oil'],
    ['Vitis vinifera seed oil', 'Grapeseed oil', 'Vynuogių kauliukų aliejus'],
    ['Persea gratissima oil', 'Avocado oil', 'Avokadų aliejus'],
    ['Ricinus communis seed oil', 'Castor oil', 'Ricinos aliejus'],
    ['Macadamia ternifolia seed oil', 'Macadamia oil'],
    ['Camellia japonica seed oil', 'Camellia oil'],
    ['Limnanthes alba seed oil', 'Meadowfoam oil'],
    ['Oenothera biennis oil', 'Evening primrose oil', 'Nakvišų aliejus'],
    ['Borago officinalis seed oil', 'Borage oil'],
    ['Cannabis sativa seed oil', 'Hemp seed oil', 'Kanapių sėklų aliejus'],
    ['Linum usitatissimum seed oil', 'Linseed oil', 'Flaxseed oil', 'Linų sėmenų aliejus'],
    ['Sesamum indicum seed oil', 'Sesame oil'],
    ['Sclerocarya birrea seed oil', 'Marula oil'],
    ['Hippophae rhamnoides oil', 'Sea buckthorn oil', 'Šaltalankių aliejus'],
    ['Calophyllum inophyllum seed oil', 'Tamanu oil'],
    ['Moringa oleifera seed oil', 'Moringa oil'],
    ['Opuntia ficus-indica seed oil', 'Prickly pear seed oil'],
    ['Glycine soja oil', 'Soybean oil'],
    ['Carthamus tinctorius seed oil', 'Safflower oil'],
    ['Crambe abyssinica seed oil', 'Abyssinian oil'],
    ['Orbignya oleifera seed oil', 'Babassu oil'],
    ['Punica granatum seed oil', 'Pomegranate seed oil'],
    ['Rubus idaeus seed oil', 'Raspberry seed oil'],
  ],
  barrier: [
    ['Ceramide NP', 'Ceramide 3'],
    ['Ceramide AP', 'Ceramide 6 II'],
    ['Ceramide EOP', 'Ceramide 1'],
    ['Ceramide NS', 'Ceramide 2'],
    'Ceramide AS',
    'Ceramide NG',
    'Phytosphingosine',
    'Sphingosine',
    'Cholesterol',
    'Linoleic acid',
    'Phytosterols',
    'Hydrogenated lecithin',
  ],
  silicone: [
    'Dimethicone',
    ['Cyclopentasiloxane', 'D5'],
    ['Cyclohexasiloxane', 'D6'],
    'Cyclomethicone',
    'Dimethiconol',
    'Dimethicone crosspolymer',
    'Dimethicone/vinyl dimethicone crosspolymer',
    'Phenyl trimethicone',
    'Caprylyl methicone',
    'Cetyl dimethicone',
    'Trimethylsiloxysilicate',
    'Polysilicone-11',
    'PEG-10 dimethicone',
    'Cetyl PEG/PPG-10/1 dimethicone',
  ],
  cleanser: [
    ['Sodium lauryl sulfate', 'SLS'],
    ['Sodium laureth sulfate', 'SLES'],
    'Ammonium lauryl sulfate',
    'Ammonium laureth sulfate',
    'Sodium myreth sulfate',
    'Sodium C14-16 olefin sulfonate',
    'Cocamidopropyl betaine',
    'Coco-betaine',
    'Coco-glucoside',
    'Decyl glucoside',
    'Lauryl glucoside',
    ['Sodium cocoyl isethionate', 'SCI'],
    'Sodium lauroyl methyl isethionate',
    'Sodium lauroyl sarcosinate',
    'Sodium cocoyl glutamate',
    'Sodium methyl cocoyl taurate',
    'Disodium laureth sulfosuccinate',
    'Disodium cocoamphodiacetate',
    'Sodium cocoamphoacetate',
    'Cocamide MEA',
    'Cocamide DEA',
    'Potassium cocoate',
    'Sodium cocoate',
    'Sodium palmate',
  ],
  emulsifier: [
    'Glyceryl stearate',
    'Glyceryl stearate SE',
    'Glyceryl stearate citrate',
    'PEG-100 stearate',
    'Ceteareth-20',
    'Steareth-2',
    'Steareth-21',
    'Cetearyl glucoside',
    'Arachidyl glucoside',
    'Cetearyl olivate',
    'Sorbitan olivate',
    'Sorbitan stearate',
    'Potassium cetyl phosphate',
    'Methyl glucose sesquistearate',
    'Polyglyceryl-2 dipolyhydroxystearate',
    'Polyglyceryl-3 diisostearate',
    'Lecithin',
    'Polysorbate 20',
    'Polysorbate 80',
    'PEG-40 hydrogenated castor oil',
    'Laureth-7',
  ],
  thickener: [
    'Xanthan gum',
    'Carbomer',
    'Acrylates/C10-30 alkyl acrylate crosspolymer',
    'Ammonium acryloyldimethyltaurate/VP copolymer',
    'Hydroxyethyl acrylate/sodium acryloyldimethyl taurate copolymer',
    'Sodium polyacrylate',
    'Polyacrylate crosspolymer-6',
    'Polyacrylamide',
    'Hydroxyethylcellulose',
    'Cellulose gum',
    'Sclerotium gum',
    'Gellan gum',
    'Hydroxypropyl starch phosphate',
    ['Tapioca starch', 'Tapijokos krakmolas'],
    ['Zea mays starch', 'Corn starch', 'Kukurūzų krakmolas'],
    'Silica',
    'Magnesium aluminum silicate',
    ['Kaolin', 'White clay', 'Baltasis molis'],
    ['Bentonite', 'Bentonite clay'],
    'Talc',
    'Nylon-12',
    ['Sodium chloride', 'Salt', 'Druska'],
    ['Charcoal powder', 'Activated charcoal', 'Aktyvuota anglis'],
  ],
  solvent: [
    ['Aqua', 'Water', 'Eau', 'Vanduo'],
    ['Alcohol', 'Ethanol', 'Ethyl alcohol'],
    ['Alcohol denat.', 'Denatured alcohol', 'SD alcohol'],
    'Isopropyl alcohol',
    'Dipropylene glycol',
    'Hexylene glycol',
  ],
  preservative: [
    'Phenoxyethanol',
    'Ethylhexylglycerin',
    'Sodium benzoate',
    'Potassium sorbate',
    'Benzyl alcohol',
    'Benzoic acid',
    'Sorbic acid',
    'Dehydroacetic acid',
    'Methylparaben',
    'Ethylparaben',
    'Propylparaben',
    'Butylparaben',
    ['Methylisothiazolinone', 'MIT'],
    ['Methylchloroisothiazolinone', 'CMIT'],
    'DMDM hydantoin',
    'Imidazolidinyl urea',
    'Diazolidinyl urea',
    'Chlorphenesin',
    'Caprylyl glycol',
    '1,2-Hexanediol',
    'Sodium levulinate',
    'Sodium anisate',
  ],
  fragrance: [
    ['Parfum', 'Fragrance', 'Perfume', 'Kvapiosios medžiagos', 'Kvepalai'],
    'Limonene',
    'Linalool',
    'Citronellol',
    'Geraniol',
    'Citral',
    'Eugenol',
    'Isoeugenol',
    'Coumarin',
    'Farnesol',
    'Hexyl cinnamal',
    'Amyl cinnamal',
    'Cinnamal',
    'Cinnamyl alcohol',
    'Benzyl salicylate',
    'Benzyl benzoate',
    'Alpha-isomethyl ionone',
    'Hydroxycitronellal',
    ['Butylphenyl methylpropional', 'Lilial'],
    'Anise alcohol',
    ['Evernia prunastri extract', 'Oakmoss'],
    ['Lavandula angustifolia oil', 'Lavender oil', 'Levandų aliejus'],
    ['Citrus aurantium dulcis peel oil', 'Orange oil', 'Apelsinų aliejus'],
    ['Citrus limon peel oil', 'Lemon oil', 'Citrinų aliejus'],
    ['Citrus aurantium bergamia peel oil', 'Bergamot oil'],
    ['Mentha piperita oil', 'Peppermint oil', 'Pipirmėčių aliejus'],
    ['Eucalyptus globulus leaf oil', 'Eucalyptus oil', 'Eukaliptų aliejus'],
    ['Menthol', 'Mentolis'],
    'Camphor',
  ],
  phAdjuster: [
    ['Citric acid', 'Citrinų rūgštis'],
    'Sodium citrate',
    'Sodium hydroxide',
    'Potassium hydroxide',
    'Triethanolamine',
    'Aminomethyl propanol',
    'Tromethamine',
    'Arginine',
    'Tartaric acid',
  ],
  chelator: [
    'Disodium EDTA',
    'Tetrasodium EDTA',
    'Trisodium ethylenediamine disuccinate',
    'Tetrasodium glutamate diacetate',
    'Pentasodium pentetate',
    'Sodium phytate',
    'Phytic acid',
  ],
  antioxidant: [
    ['Tocopherol', 'Vitamin E', 'Vitaminas E'],
    ['Tocopheryl acetate', 'Vitamin E acetate'],
    ['Ferulic acid', 'Ferulo rūgštis'],
    'Resveratrol',
    ['Ubiquinone', 'Coenzyme Q10', 'CoQ10', 'Kofermentas Q10'],
    'Astaxanthin',
    'Ergothioneine',
    'Glutathione',
    ['Thioctic acid', 'Alpha lipoic acid'],
    'Idebenone',
    ['Caffeine', 'Kofeinas'],
    'Ascorbyl palmitate',
    'BHT',
    ['Camellia sinensis leaf extract', 'Green tea extract', 'Žaliosios arbatos ekstraktas'],
    ['Rosmarinus officinalis leaf extract', 'Rosemary extract'],
  ],
  vitaminC: [
    ['Ascorbic acid', 'Vitamin C', 'L-ascorbic acid', 'Vitaminas C', 'Askorbo rūgštis'],
    ['Sodium ascorbyl phosphate', 'SAP'],
    ['Magnesium ascorbyl phosphate', 'MAP'],
    ['Ascorbyl glucoside', 'AA2G'],
    'Ethyl ascorbic acid',
    '3-O-ethyl ascorbic acid',
    ['Tetrahexyldecyl ascorbate', 'THD ascorbate', 'Ascorbyl tetraisopalmitate'],
  ],
  retinoid: [
    ['Retinol', 'Vitamin A', 'Vitaminas A'],
    ['Retinal', 'Retinaldehyde'],
    'Retinyl palmitate',
    'Retinyl acetate',
    'Retinyl propionate',
    ['Hydroxypinacolone retinoate', 'HPR', 'Granactive retinoid'],
    'Adapalene',
    ['Tretinoin', 'Retinoic acid'],
    'Tazarotene',
    'Trifarotene',
  ],
  exfoliant: [
    ['Glycolic acid', 'Glikolio rūgštis'],
    ['Lactic acid', 'Pieno rūgštis'],
    ['Mandelic acid', 'Migdolų rūgštis'],
    ['Malic acid', 'Obuolių rūgštis'],
    ['Salicylic acid', 'Salicilo rūgštis'],
    'Betaine salicylate',
    ['Capryloyl salicylic acid', 'LHA'],
    ['Gluconolactone', 'PHA'],
    'Lactobionic acid',
    ['Papain', 'Papaya enzyme'],
    ['Bromelain', 'Pineapple enzyme'],
  ],
  peptide: [
    'Palmitoyl tripeptide-1',
    'Palmitoyl tetrapeptide-7',
    ['Palmitoyl pentapeptide-4', 'Matrixyl'],
    'Palmitoyl tripeptide-5',
    ['Acetyl hexapeptide-8', 'Argireline', 'Acetyl hexapeptide-3'],
    ['Acetyl octapeptide-3', 'SNAP-8'],
    'Acetyl tetrapeptide-5',
    ['Dipeptide diaminobutyroyl benzylamide diacetate', 'Syn-Ake'],
    ['Copper tripeptide-1', 'GHK-Cu', 'Copper peptide', 'Vario peptidai'],
    ['Hydrolyzed collagen', 'Collagen', 'Kolagenas'],
    'Soluble collagen',
  ],
  antiAgeing: ['Adenosine', 'Bakuchiol'],
  soothing: [
    'Allantoin',
    ['Bisabolol', 'Alpha-bisabolol'],
    ['Centella asiatica extract', 'Cica', 'Gotu kola', 'Azijinė centelė'],
    'Madecassoside',
    'Asiaticoside',
    'Asiatic acid',
    ['Aloe barbadensis leaf juice', 'Aloe vera', 'Alavijas'],
    'Dipotassium glycyrrhizate',
    ['Avena sativa kernel flour', 'Colloidal oatmeal'],
    ['Avena sativa kernel extract', 'Oat extract', 'Avižų ekstraktas'],
    ['Chamomilla recutita flower extract', 'Chamomile extract', 'Ramunėlių ekstraktas'],
    ['Calendula officinalis flower extract', 'Calendula extract', 'Medetkų ekstraktas'],
    ['Hamamelis virginiana water', 'Witch hazel'],
    ['Cucumis sativus fruit extract', 'Cucumber extract', 'Agurkų ekstraktas'],
    ['Portulaca oleracea extract', 'Purslane extract'],
    ['Houttuynia cordata extract', 'Heartleaf extract'],
    ['Propolis extract', 'Propolis', 'Pikis'],
    'Beta-glucan',
    'Bifida ferment lysate',
    'Ectoin',
  ],
  brightening: [
    ['Niacinamide', 'Vitamin B3', 'Nicotinamide', 'Vitaminas B3'],
    ['Tranexamic acid', 'Traneksamo rūgštis'],
    'Alpha-arbutin',
    'Arbutin',
    'Kojic acid',
    'Hydroquinone',
    ['4-Butylresorcinol', 'Rucinol'],
    'Hexylresorcinol',
    ['Isobutylamido thiazolyl resorcinol', 'Thiamidol'],
    ['Acetyl glucosamine', 'N-acetyl glucosamine', 'NAG'],
    ['Glycyrrhiza glabra root extract', 'Licorice root extract', 'Saldymedžio ekstraktas'],
    'Galactomyces ferment filtrate',
  ],
  acne: [
    ['Benzoyl peroxide', 'BPO', 'Benzoilo peroksidas'],
    ['Azelaic acid', 'Azelaino rūgštis'],
    'Potassium azeloyl diglycinate',
    ['Sulfur', 'Siera'],
    'Zinc PCA',
    'Zinc gluconate',
    ['Melaleuca alternifolia leaf oil', 'Tea tree oil', 'Arbatmedžio aliejus'],
  ],
  antiDandruff: [
    'Piroctone olamine',
    'Zinc pyrithione',
    'Ketoconazole',
    'Selenium sulfide',
    'Climbazole',
  ],
  sunscreen: [
    ['Zinc oxide', 'Cinko oksidas'],
    ['Titanium dioxide', 'Titano dioksidas'],
    ['Butyl methoxydibenzoylmethane', 'Avobenzone'],
    ['Ethylhexyl methoxycinnamate', 'Octinoxate'],
    'Octocrylene',
    'Homosalate',
    ['Ethylhexyl salicylate', 'Octisalate'],
    ['Benzophenone-3', 'Oxybenzone'],
    ['Bis-ethylhexyloxyphenol methoxyphenyl triazine', 'Bemotrizinol', 'Tinosorb S'],
    ['Methylene bis-benzotriazolyl tetramethylbutylphenol', 'Bisoctrizole', 'Tinosorb M'],
    ['Diethylamino hydroxybenzoyl hexyl benzoate', 'Uvinul A Plus', 'DHHB'],
    ['Ethylhexyl triazone', 'Uvinul T 150'],
    ['Diethylhexyl butamido triazone', 'Iscotrizinol'],
    ['Terephthalylidene dicamphor sulfonic acid', 'Ecamsule', 'Mexoryl SX'],
    ['Drometrizole trisiloxane', 'Mexoryl XL'],
    ['Phenylbenzimidazole sulfonic acid', 'Ensulizole'],
    ['Tris-biphenyl triazine', 'Tinosorb A2B'],
    ['Methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate', 'Mexoryl 400'],
    ['Disodium phenyl dibenzimidazole tetrasulfonate', 'Bisdisulizole disodium'],
    ['Polysilicone-15', 'Parsol SLX'],
    ['Isoamyl p-methoxycinnamate', 'Amiloxate'],
  ],
  colourant: [
    'Mica',
    'Iron oxides',
    'CI 77491',
    'CI 77492',
    'CI 77499',
    'CI 77891',
    'CI 19140',
    'CI 42090',
    'CI 16035',
  ],
  hair: [
    'Behentrimonium chloride',
    'Behentrimonium methosulfate',
    'Cetrimonium chloride',
    'Stearamidopropyl dimethylamine',
    'Polyquaternium-10',
    'Polyquaternium-7',
    'Guar hydroxypropyltrimonium chloride',
    'Amodimethicone',
    'Bis-aminopropyl dimethicone',
    ['Hydrolyzed keratin', 'Keratin', 'Keratinas'],
    'Hydrolyzed wheat protein',
    'Hydrolyzed silk',
    ['Biotin', 'Vitamin B7', 'Vitamin H', 'Biotinas'],
    ['Rosmarinus officinalis leaf oil', 'Rosemary oil', 'Rozmarinų aliejus'],
  ],
  plantExtract: [
    ['Rosa damascena flower water', 'Rose water', 'Rožių vanduo'],
    ['Salix alba bark extract', 'Willow bark extract', 'Gluosnio žievės ekstraktas'],
    ['Ginkgo biloba leaf extract', 'Ginkgo extract'],
    ['Panax ginseng root extract', 'Ginseng extract', 'Ženšenio ekstraktas'],
    ['Curcuma longa root extract', 'Turmeric extract', 'Ciberžolės ekstraktas'],
    ['Urtica dioica leaf extract', 'Nettle extract', 'Dilgėlių ekstraktas'],
    ['Arctium lappa root extract', 'Burdock root extract', 'Varnalėšų ekstraktas'],
    ['Coffea arabica seed extract', 'Coffee extract', 'Kavos ekstraktas'],
    ['Algae extract', 'Seaweed extract', 'Dumblių ekstraktas'],
    ['Vitis vinifera fruit extract', 'Grape extract'],
  ],
};

export const ingredientCatalog: readonly CatalogEntry[] = catalogCategories.flatMap((category) =>
  byCategory[category].map((item): CatalogEntry => {
    const [name, ...aliases] = typeof item === 'string' ? [item] : item;
    return { name, category, aliases };
  }),
);

let byNormalized: Map<string, CatalogEntry> | null = null;

/** The catalogue entry for a normalised name (`normalizeName`), if the name is in it. */
export function catalogEntry(normalizedName: string): CatalogEntry | undefined {
  byNormalized ??= new Map(ingredientCatalog.map((e) => [normalizeName(e.name), e]));
  return byNormalized.get(normalizedName);
}
