import { router } from 'expo-router';
import { Fragment } from 'react';
import { ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTranslation } from 'react-i18next';

import { Card } from '@/components/ui/card';
import { ListRow } from '@/components/ui/list-row';
import { ScreenHeader } from '@/components/ui/screen-header';
import { Separator } from '@/components/ui/separator';
import { Text } from '@/components/ui/text';

import licences from '../licences.json';

/** Open-source packages the app ships with (generated by `pnpm run licences`). */
export function LicencesScreen() {
  const { t } = useTranslation();
  return (
    <SafeAreaView edges={['top']} className="flex-1 bg-canvas">
      <ScreenHeader title={t('screens.licences')} onBack={() => router.back()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 16, paddingBottom: 32 }}>
        <Text className="text-body text-ink-muted">{t('settings.licencesIntro')}</Text>
        <Card flush>
          {licences.map((l, i) => (
            <Fragment key={l.name}>
              {i > 0 ? <Separator className="ml-4" /> : null}
              <ListRow label={l.name} detail={l.version} value={l.license} trailing="value" />
            </Fragment>
          ))}
        </Card>
      </ScrollView>
    </SafeAreaView>
  );
}
